# Settings for the app
app:
  # HTML Title
  title: Shareabouts
  # Header name
  name: Shareabouts
  # Meta description that will show up in Google search results
  meta_description: _(Shareabouts is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.)
  # Meta author that will show up in Google search results
  meta_author: OpenPlans.org


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: true
  geocode_field_label: _(Enter an address...)
  # geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  options:
    center:
      lat: -37.86429976467348
      lng: 144.75036931090506
    zoom: 12
    minZoom: 10
    maxZoom: 20
    maxBounds: [[-37.980267, 144.571255], [-37.774908, 144.991692]]
  layers:
    # - url: http://{s}.tiles.mapbox.com/v3/openplans.h7ab4o5f/{z}/{x}/{y}.png
    # - url: https://api.mapbox.com/v4/creativesuburbs.nopd3hff/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw
    #   attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'
    # https://api.mapbox.com/styles/v1/creativesuburbs/cio2qdxaf000047nkd0n8ef19.html?title=true&access_token=pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw#12.100116128538621/-37.86429976467348/144.75036931090506/0
    # https://api.mapbox.com/styles/v1/creativesuburbs/cio2qdxaf000047nkd0n8ef19/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw
    - url: https://api.mapbox.com/styles/v1/creativesuburbs/cio2qdxaf000047nkd0n8ef19/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw
      minZoom: 5
      maxZoom: 13
    - url: https://api.mapbox.com/styles/v1/creativesuburbs/cio4507ml006xbvm8maitofdq/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw
      minZoom: 13
      maxZoom: 15
      # bounds: [[-37.875440, 144.713211], [-37.850918, 144.752568]]
    - url: https://api.mapbox.com/styles/v1/creativesuburbs/cio4aefm6002qydnkfw2wtmby/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw
      minZoom: 16
      maxZoom: 20
      # bounds: [[-37.860815, 144.735140], [-37.857230, 144.741867]]
    # - type: mapbox
    #   style: mapbox://styles/creativesuburbs/cio2qdxaf000047nkd0n8ef19
    #   accessToken: pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw
    #   # url: https://api.mapbox.com/v4/creativesuburbs.nopd3hff/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiY3JlYXRpdmVzdWJ1cmJzIiwiYSI6ImNpZzBnY3VtODA1d2N1d2x2MmQwYjY0ZnIifQ.Y_4BPGe8c65zVdv8nHNZuw
    # - url: /static/data/philadelphia.geojson
    #   type: json
    #   rules:
    #     - condition: 'true'
    #       style:
    #         color: "#444"
    #         opacity: 0.6
    #         fillOpacity: 0.1
    #         weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  vegetation:
    label: _(Vegetation)
    rules:
      - condition: '"{{location_type}}" === "vegetation"'
        icon:
          iconUrl: /static/css/images/pins/pin_vegetation.png
          iconSize: [36, 53]
          iconAnchor: [18, 53]

  amenities:
    label: _(Amenities)
    rules:
      - condition: '"{{location_type}}" === "amenities"'
        icon:
          iconUrl: /static/css/images/pins/pin_amenities.png
          iconSize: [36, 53]
          iconAnchor: [18, 53]

  recreational:
    label: _(Recreational facilities)
    rules:
      - condition: '"{{location_type}}" === "recreational"'
        icon:
          iconUrl: /static/css/images/pins/pin_recreational.png
          iconSize: [36, 53]
          iconAnchor: [18, 53]

  gettingaround:
    label: _(Getting around)
    rules:
      - condition: '"{{location_type}}" === "gettingaround"'
        icon:
          iconUrl: /static/css/images/pins/pin_gettingaround.png
          iconSize: [36, 53]
          iconAnchor: [18, 53]

  other:
    label: _(Other ideas)
    rules:
      - condition: '"{{location_type}}" === "other"'
        icon:
          iconUrl: /static/css/images/pins/pin_other.png
          iconSize: [36, 53]
          iconAnchor: [18, 53]


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Place)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Ideas)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
    - prompt: _(Location Name)
      type: text
      name: name
      optional: true
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(Location Type)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Vegetation)
          value: vegetation
        - label: _(Amenities)
          value: amenities
        - label: _(Recreational facilities)
          value: recreational
        - label: _(Getting around)
          value: gettingaround
        - label: _(Other ideas)
          value: other
      name: location_type
      attrs:
        - key: required
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
        - key: rows
          value: 2
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments
  adding_supported: true

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  adding_supported: true
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(FAQs)
    slug: faq
    name: faq

  - title: _(Greening the Pipeline)
    external: true
    url: http://www.greeningthepipeline.com.au

  - title: Filter Ideas
    slug: filter-type
    pages:
      - title: All
        external: true
        url: /filter/all
      - title: _(Vegetation)
        url: /filter/vegetation
        external: true
      - title: _(Amenities)
        url: /filter/amenities
        external: true
      - title: _(Recreational facilities)
        url: /filter/recreational
        external: true
      - title: _(Getting around)
        url: /filter/gettingaround
        external: true
      - title: _(Other ideas)
        url: /filter/other
        external: true

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
